name: Build example

on:
  push:
    branches: [ main ]
    paths-ignore: [ '**.md' ]
  pull_request:
    branches: [ main ]
    paths-ignore: [ '**.md' ]

jobs:
  build-stable-beta:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        channel: [ 'stable', 'beta' ]
    defaults:
      run:
        working-directory: ./example
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - uses: subosito/flutter-action@v2.4.0
        with:
          channel: ${{ matrix.channel }}

      - name: Print Dart SDK version
        run: dart --version

      - name: Print Flutter SDK version
        run: flutter --version

      - name: Install dependencies
        run: flutter pub get

      - name: Format code
        if: ${{ matrix.channel == 'stable' }}
        run: dart format lib --set-exit-if-changed

      - name: Analyze
        run: flutter analyze lib

      - name: Build APK
        run: flutter build apk --no-shrink

  build-old-versions:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: [ '3.19.6', '3.22.0' ]
    defaults:
      run:
        working-directory: ./example
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - uses: subosito/flutter-action@v2.4.0
        with:
          flutter-version: ${{ matrix.version }}

      - name: Print Dart SDK version
        run: dart --version

      - name: Print Flutter SDK version
        run: flutter --version

      - name: Install dependencies
        run: flutter pub get

      - name: Build APK
        run: flutter build apk --debug --no-shrink
